CREATE TABLE IF NOT EXISTS Episodes
(
EpisodeID INT (15) NOT NULL AUTO_INCREMENT,
VideoContentID INT (20) NOT NULL,
GenreID INT (10) NOT NULL,
EpisodeName VARCHAR (20) NOT NULL,
EpisodeDescription VARCHAR (50) NOT NULL,
Views INT (10) NOT NULL,
CONSTRAINT pk_EpisodeID PRIMARY KEY (EpisodeID)
)